
- model: modular
  description: A sample model
  label: mod
  sourcecode:
    - exclude: '*swp'
    - exclude: 'tags'
    - exclude: '__pycache__/'
  output-scalars:
    step: 'step: (\step)'
    loss: 'loss: (\value)'
    val_loss: 'last val: (\value)'
    ent: 'ent: (\value)'
  operations:

    small:
      main: main
      description: Train a very small model just to test
      label: small
      sourcecode:
        - exclude: '*swp'
        - exclude: 'tags'
        - exclude: '__pycache__*'
      flags:
        line_return: True
        embed_dim: 121
        emb_chunks: 3
        num_embeddings: 10
        num_hiddens: 10
        batch_size: 64
        print_every: 10
        num_epochs: 100
        toy_dataset_size: 1000
      output-scalars:
        step: 'step: (\step)'
        loss: 'loss: (\value)'
        val_loss: 'last val: (\value)'
        ent: 'ent: (\value)'

    med:
      main: main
      description: Search a few hparams
      label: mod
      flags:
        line_return: True
        embed_dim: 121
        emb_chunks: 3
        num_embeddings: 10
        num_hiddens: 256
        batch_size: 256
        print_every: 100
        num_epochs: 200
        toy_dataset_size: 20000
      output-scalars:
        step: 'step: (\step)'
        loss: 'loss: (\value)'
        diff: 'diff: (\value)'
        val_loss: 'last val: (\value)'
        ent: 'ent: (\value)'

    search_smaller_fn:
      main: main
      description: Search a few hparams
      label: mod_mid
      flags:
        line_return: True
        seed: [521, 1, 2, 3, 4]
        embed_dim: 36
        dec_input_size: 5
        dec_h_size: 5
        emb_chunks: 3
        num_embeddings: 10
        num_hiddens: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
        batch_size: 256
        print_every: 100
        num_epochs: 400
        toy_dataset_size: 50000
      output-scalars:
        step: 'step: (\step)'
        loss: 'loss: (\value)'
        diff: 'diff: (\value)'
        val_loss: 'last val: (\value)'
        ent: 'ent: (\value)'

